---
title: "HW_3"
author: "Hector Santana"
date: "10/21/2021"
output: pdf_document
---

# Library Loading

```{r warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
library(data.table)
library(VIM)
library(mice)
library(Rcpp)
library(corrplot)
library(stats)
library(rstatix)
library(DataExplorer)
library(caret)
library(psych)
library(janitor)
library(DMwR)
```

# Data Exploration

```{r Data_Importation}

eval_data = read.csv("https://raw.githubusercontent.com/manonfire86/Data621/main/HW_3/crime-evaluation-data_modified.csv")

training_data = read.csv("https://raw.githubusercontent.com/manonfire86/Data621/main/HW_3/crime-training-data_modified.csv")

```

```{r Data_Exploration}

## Initial Analysis of data structures

head(eval_data,5)

head(training_data,5)
```


```{r Data_Exploration_2}

## Initial Analysis of data structures (cont'd)

str(eval_data)
str(training_data)

```
```{r Data_Exploration_3}

## Data Set Comparison

list(training_data,eval_data) %>% compare_df_cols() %>% `colnames<-`(c('Column Name', 'Training', 'Evaluation'))
```


```{r Data_Exporation_4}
training_data  %>% describe()
```

```{r Data_Exploration_5}

training_data  %>% plot_histogram()
training_data %>% plot_density()
training_data %>% plot_boxplot(by="target")

```
```{r Data_Exploration_6}
training_data  %>% plot_missing()
training_data  %>% gather(variable, value) %>% filter(value == 0) %>% 
  group_by(variable) %>% tally() %>% mutate(percent = n / nrow(training) * 100) %>%
  mutate(percent = paste0(round(percent, ifelse(percent < 10, 1, 0)), "%")) %>%
  arrange(desc(n)) %>% rename(`Variable With Zeros` = variable, 
                              `Number of Records` = n,
                              `Share of Total` = percent)
```


# Data Preparation

